import { Sen } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import ConditionalLayout from "../components/ConditionalLayout";

const getSen = Sen({
  variable: "--font-get-sen",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${getSen.variable} antialiased`}>
        <Providers>
          <ConditionalLayout>{children}</ConditionalLayout>
        </Providers>
      </body>
    </html>
  );
}
