import { Sen } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/page";
import Footer from "../components/Footer/page";
import Providers from "./Providers";

const getSen = Sen({
  variable: "--font-get-sen",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${getSen.variable} antialiased`}>
        <Providers>
          <Navbar />
          <div className="min-h-screen mt-14">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
